version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo-stack
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  server:
    image: jacksonet00/demo-stack
    depends_on:
      - db
    ports:
      - '5000:5000'
    environment:
      FLASK_DEBUG: 'True'
      FLASK_ENV: development
      SECRET_KEY: asdftyuiopasdf
      JWT_SECRET_KEY: lkjhasdfyuop
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/demo-stack'
      DB_HOST: 0.0.0.0
      PORT: 5000
      ENV: __dev__
